### ISSUE TITLE
定义文件与代码不一致

### ISSUE THREAD

**Issue by lzy2014love** [JserWang/vite-plugin-faker#1]
npm包中， d.ts定义文件与构建后mjs文件的导出不一致
![image](https://user-images.githubusercontent.com/23011780/115944807-ac99df80-a4ea-11eb-8d27-47ac116b4adf.png)
![image](https://user-images.githubusercontent.com/23011780/115944814-b9b6ce80-a4ea-11eb-9357-38b0c0f39338.png)
![image](https://user-images.githubusercontent.com/23011780/115944823-c3d8cd00-a4ea-11eb-98aa-4d649103a6ba.png)

**Comment by JserWang** [comment]
感谢指正，已将用法更新至 `README` 中 ，如在使用中还有其他疑问，可继续提 `issue`。

```typescript
import vitePluginFaker from 'vite-plugin-faker';
import { defineConfig } from 'vite';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: {
    vitePluginFaker({
      basePath: 'src/apis',
      mockDir: '/mock',
      includes: [/^.Service/],
      watchFile: true
    })
  }
});
```
